<?php
/*
 * This file is part of the Eko\FeedBundle Symfony bundle.
 *
 * (c) Vincent Composieux <vincent.composieux@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eko\FeedBundle\Formatter;

/**
 * Formatter interface
 *
 * This interface contains the methods that a renderer needs to implement
 *
 * @author Vincent Composieux <vincent.composieux@gmail.com>
 */
interface FormatterInterface
{
    /**
     * Initialize formatter XML format
     *
     * @abstract
     */
    public function initialize();

    /**
     * This method render the feed in format generated by formatter
     *
     * @abstract
     * @return string
     */
    public function render();
}